### ISSUE TITLE
契約日と入居日と賃料発生日について

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#1]
この辺りが不透明なのでつらい

**Comment by potato4d** [comment]
不動産会社によって、契約日から賃料が発生する場合と、入居日から賃料が発生する場合があるらしい
https://www.kurachic.jp/column/chintai/LookingRoom/20151002185620.html

**Comment by p-chan** [comment]
SUUMOのおねえさんが、「契約日から2週間以内にはお支払いいただくというのが一般的ですかね〜」とおっしゃっていた。
9月入居の場合、8月中旬に契約するのがベストということらしい。

**Comment by potato4d** [comment]
なるほど。とりあえずじゃあ家取り置きいけるなら取り置きして、契約自体を8月中旬とかできたらベストなのかな。

**Comment by p-chan** [comment]
「入居日にかかわらず、契約日の2週間後に賃料が発生するのがデファクトである」

**Comment by p-chan** [comment]
@potato4d 残念だけど、取り置きは無理っぽい雰囲気があった。(あと、このissueに関してはクリア出来たと思ったのでクローズしました。続きは家を決めるの方でやりましょい。)
