### ISSUE TITLE
内覧に行く

### ISSUE THREAD

**Issue by p-chan** [the-house-of-ohnin/issues#10]
18日 7時 京都駅
- [x] 内覧のアポを取る
- [x] オタクのアポを取る
#3

**Comment by potato4d** [comment]
オタクのアポとれた

**Comment by potato4d** [comment]
@p1ch-jp 
内覧アポはSuumo？

**Comment by p-chan** [comment]
とりあえず18日休み取れたというご報告

内覧アポはSuumoでいこうと思います
明日電話します

**Comment by p-chan** [comment]
電話しました.
物件のオーナーさんに連絡をとったのち, 折り返し電話をいただけるとのことです.

**Comment by potato4d** [comment]
athomeの方が礼金ナシで神なのでathomeにします

**Comment by potato4d** [comment]
今日は定休日とのことなので、木曜の朝（多分米原か大垣の乗り換え待ち中）に電話で

**Comment by potato4d** [comment]
@p1ch-jp

**Comment by p-chan** [comment]
# 内覧について

渋谷駅でPとP4Dが待ち合わせ・新宿駅でしろたまを拾って,
12:00にTOKYOヘヤサガス 新宿南口店を訪問する.

SI渋谷と他数件を内覧する.

**Comment by p-chan** [comment]
TOKYOヘヤサガス 新宿南口店
〒162-0022 東京都新宿区新宿3丁目32-2 MOTOビル4F

**Comment by potato4d** [comment]
「TOKYOヘヤサガス。」での内覧の結果、以下の二件について、申し込みを行った。
審査の後、審査通過の場合は二件から決定し、9月より入居。
しろたまについては、本人はいいものの、親の説得次第か。
- セントアイヴス渋谷
- メゾンハラ
