### ISSUE TITLE
メンバーの総偏差値が低い

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#16]

**Comment by p-chan** [comment]
ワイハイフン, 低目の見物.

**Comment by p-chan** [comment]
でもさ、全員ハイフンだし計測不可能じゃね！？
これ偏差値120ワンチャンあるでしょｗｗｗｗｗｗ

**Comment by p-chan** [comment]
![ss_ 2016-08-19 at 22 14 58](https://cloud.githubusercontent.com/assets/7752475/17810836/6d56dacc-665a-11e6-8505-5c6c5d191cee.jpg)
