### ISSUE TITLE
しろたまの生活について

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#17]
しろたまが出来ること
- [ ] 料理
- [ ] 洗濯
- [ ] 洗い物
- [x] 掃除(自分の範囲は汚さない、虫を出さない)
- [x] 風呂掃除
- [x] ゴミ出し

しろたまが生活するための工夫
- 皿を落として割らないように、木製の皿を用意する。
- トイレを詰まらせて流すおそれがあるので、入居条件に「詰まっているときは水を流さない」を追加する
- 間違えてリポジトリを消してしまわないよう、GitHubの権限はMemberにする。
- コインランドリーは旅立たせると帰ってこないので、なれるまでは1人ではいかせない

**Comment by p-chan** [comment]
皿を落として割らないように、木製の皿を用意する。

**Comment by sirotama** [comment]
しねばか

**Comment by potato4d** [comment]
トイレを詰まらせて流すおそれがあるので、
入居条件に「詰まっているときは水を流さない」を追加する

**Comment by sirotama** [comment]
@p1ch-jp 死ね障害

**Comment by p-chan** [comment]
@sirotama 悲しい＞＜

**Comment by potato4d** [comment]
間違えてリポジトリを消してしまわないよう、GitHubの権限はMemberにする。

**Comment by potato4d** [comment]
コインランドリーは旅立たせると帰ってこないので、なれるまでは1人ではいかせない

**Comment by potato4d** [comment]
@sirotama 
取り敢えず家事出来ることチェックリストつくろうよ

**Comment by potato4d** [comment]
@sirotama 
- [ ] 料理
- [ ] 洗濯
- [ ] 洗い物
- [x] 掃除(自分の範囲は汚さない、虫を出さない)
- [x] 風呂掃除
- [x] ゴミ出し

**Comment by p-chan** [comment]
@potato4d じゅうぶん

**Comment by sirotama** [comment]
じっぷん　だぞ

**Comment by p-chan** [comment]
@sirotama ハイフンに漢字の間違い指摘するのは酷だし勘弁して＞＜
