### ISSUE TITLE
資金が不足しそう

### ISSUE THREAD

**Issue by p-chan** [the-house-of-ohnin/issues#19]
当初、入居にあたっての初期費用は、1ヶ月目の家賃 + 敷金 + 礼金の合計家賃3ヶ月ぶんで考えていた。
しかし、諸々含めると家賃5~6ヶ月ぶんが必要ということが判明した。

**Comment by potato4d** [comment]
概算費用：
- セントアイヴス渋谷 70万円
- メゾンドハラ 65 or 78万円

**Comment by p-chan** [comment]
はじめ、2人で40万ずつ出すことを計画していたが、この調子だと生活必需品の類が一切調達できないことになる。

**Comment by p-chan** [comment]
現実的なアレとして、初期費用を削るのは不可能なので
1. @p1ch-jp と @potato4d で 45万ずつ出しあって確保する(予算を+10万)
2. @sirotama にも一部支払ってもらい 40万・40万・10万とかで予算を確保する(予算を+10万)
3. @sirotama にも支払ってもらい 40万・40万・40万とかで予算を確保する(予算を+40万)

のどれかなんだよなぁ...

**Comment by sirotama** [comment]
1と2合わせて45+45+10万ならワンチャンある
