### ISSUE TITLE
[WIP]ロゴをつくる

### ISSUE THREAD

**Issue by p-chan** [the-house-of-ohnin/issues#2]

**Comment by potato4d** [comment]
@p1ch-jp 
![image](https://cloud.githubusercontent.com/assets/6993514/16901129/cc169d18-4c74-11e6-8578-8f67ba337b66.png)

**Comment by p-chan** [comment]
![ohnin-logo-wip](https://cloud.githubusercontent.com/assets/7752475/17589400/94fb4118-600f-11e6-8f83-902b55eacc8b.png)
