### ISSUE TITLE
生活をするうえでの秩序を守る方法について考える

### ISSUE THREAD

**Issue by p-chan** [the-house-of-ohnin/issues#20]
## 共用部分について
- 人の善意を信じる
## 騒音問題について
- 消音時間を決める
## 喧嘩について
- しない
- 万が一起きた場合には、渋谷にてフリースタイルダンジョン開催
## 窃盗について
- 人の善意を信じる
## 友達を呼ぶことについて

迷惑をかけないひとならOK。(モノを盗まない・運営からの注意を聞く・etc...)
ただ、夜遅くまで騒ぐのはダメ。
金夜とか土夜以外は、消音時間にお帰りいただく。(泊まっていくならOK)
## 彼女を呼ぶことについて
- ダメ
## シェアハウスの閉鎖について
- 物件が定期借家のため、2年間運営する。

> 参考: http://matome.naver.jp/odai/2136561487687941201

**Comment by potato4d** [comment]
> シェアハウスの閉鎖について

これはそもそも初期については一旦2年で決まってるしよくないか（その後の継続はまた終りが近づいたら）
