### ISSUE TITLE
部屋の分割について

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#21]
SIS, MHともに、2人ならいいものの、3人となると色々と考慮すべき事項が増えるため、そこについて話す

**Comment by potato4d** [comment]
SIS

<img width="437" alt="2016-08-20 21 08 00" src="https://cloud.githubusercontent.com/assets/6993514/17831068/68974966-671a-11e6-80ed-4574950dc1b7.png">

**Comment by potato4d** [comment]
MH

<img width="283" alt="2016-08-20 21 11 41" src="https://cloud.githubusercontent.com/assets/6993514/17831083/cf1d4bb8-671a-11e6-9d3e-79a6116a4244.png">

**Comment by sirotama** [comment]
MH－モンスターハウス－なら俺が4.5の方に住んでpotato4dが6.0の方に住んで収納にPちゃんが住めば解決だぞ

**Comment by sirotama** [comment]
モンスターハウスだ！！！IoT

**Comment by potato4d** [comment]
@sirotama 
Pちゃんの人権がないでしょ

**Comment by sirotama** [comment]
@potato4d オタクに人権なんてある訳ないでしょ
