### ISSUE TITLE
オーナーに拒否される

### ISSUE THREAD

**Issue by p-chan** [the-house-of-ohnin/issues#23]
- @potato4d が未成年であるであるため名義人になれない → 社長はイケるけどダメ → #24 
- @p1ch-jp の内定通知書が無い (現在、申請中)
- @p1ch-jp の4月までの収入が不確かである -> 不動産屋「親を名義人にしては？」 -> ご家庭の経済状況がアレなのでたぶん無理

**Comment by potato4d** [comment]
なんかうちの社長が名義人になるとワンちゃんとか聴いた

**Comment by potato4d** [comment]
くぅ〜ｗ疲れました！

**Comment by p-chan** [comment]
# potato4d
- 現在、父親の就活待ち → 就職してもダメ

# p1ch-jp
- 来年4月までの収入の証明ができない
- 母に名義人になってもらうのは無理である

**Comment by p-chan** [comment]
@potato4d には共有したけど、今朝10時ころにかけた電話で言われた内容が絶望的すぎる。
