### ISSUE TITLE
親に就職してもらう

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#24]
父親がいい加減就職しないと住宅を借りることすら不可能なことが判明したので**正社員で**かつ**今週中に**就職してもらう（内定を得る）

**Comment by rinsuki** [comment]
キツすぎでしょ

**Comment by potato4d** [comment]
@Petitsurume 
こんなに心苦しい状況だしせめてミュートとブロック解除して

**Comment by rinsuki** [comment]
@potato4d そういって同情を求めながらブロック解除を求めるのは駄目だと思います。

**Comment by potato4d** [comment]
@Petitsurume 
泣いてる
