### ISSUE TITLE
家を続けるかどうかを決める

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#25]
このプロジェクトを続けるか、やめて取り敢えず各々住む所なりなんなりを探す方向に行くかを決める。

**Comment by p-chan** [comment]
玉音放送のURLを探してる

**Comment by rinsuki** [comment]
http://www.kunaicho.go.jp/kunaicho/koho/taisenkankei/syusen/syusen.html

**Comment by potato4d** [comment]
耐え難きを〜〜

**Comment by p-chan** [comment]
忍び難きを〜〜

**Comment by potato4d** [comment]
- Organizationは残す(この先ある可能性はあるので)
- しろたまはPちゃんが本日帰宅時に起きていた場合は直接（Skype）連絡。そうでない場合は明日の朝Twitterで。
- 不動産屋への連絡については、明日の昼ごろに @p1ch-jp が行う。昼休み中に不可であった場合は @potato4d で行う。
- もう一旦耐え難きは耐えず、忍び難きを忍ばない。
