### ISSUE TITLE
家を決める

### ISSUE THREAD

**Issue by p-chan** [the-house-of-ohnin/issues#3]
Child Tasks:
#10

**Comment by potato4d** [comment]
- [x] 部屋のタイプを決定する(家系とかオフィス系とか)
- [x] 内覧する部屋の候補を決定する
- [ ] 家を契約する

**Comment by potato4d** [comment]
#1 を見る限り状況芳しくないなぁ。
流れとしては8月までは動きなしで待機で、真ん中あたりに決定することになるよね。
家具とかの搬入コミコミだと9月バタバタしそう。

**Comment by p-chan** [comment]
選択肢は以下の3つだけど、まあ現実的に考えて2だと思う
1. 頑張って取り置き可能な物件を探す
2. 8月中旬まで待って契約する
3. 割りきって契約してしまう

**Comment by potato4d** [comment]
だな

**Comment by potato4d** [comment]
取り敢えずセントアイヴス渋谷を確保予定。

**Comment by potato4d** [comment]
8/18, 19で内覧予定。

**Comment by potato4d** [comment]
@p1ch-jp 
8/18か17かで18きっぷでオタクウェイの会しながらいきませんか

**Comment by p-chan** [comment]
@potato4d ええで

**Comment by potato4d** [comment]
そういえば、事前に鍵の取り扱いも決めておく必要がありそう。
多分初めに渡されるの1つだろうし、追加発行1〜2週間かかるでしょ。

**Comment by p-chan** [comment]
鍵とか一瞬で作れるのでは

**Comment by potato4d** [comment]
@p1ch-jp 
なんか18切符完全にフルバーストしそうで草

**Comment by p-chan** [comment]
チケット屋で1枚とか買えばいいのでは

**Comment by potato4d** [comment]
@p1ch-jp 
それでええんやけど、こっちの持ちチケットで行くのは厳しいかも

**Comment by potato4d** [comment]
てか内覧に行くがあるのにこっちで書いてしまったの草
