### ISSUE TITLE
生活必需品を全て揃える

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#4]
確定枠
- [ ] 机
- [ ] イス
- [ ] 電子レンジ
- [ ] 冷蔵庫
- [ ] 炊飯器
- [ ] ルーター
- [ ] 掃除機

あと要議論あればやっていきましょう。

**Comment by potato4d** [comment]
前回「なくても良い」って話だったけど、やっぱり洗濯機いる可能性ある気がしてたりする。
ここオフラインかSkype希望です。

**Comment by p-chan** [comment]
一応、昨日のSkypeの議事録として
「とりあえずはじめは洗濯機は要らないよね、後から必要になれば買い足そう」という結論に至った

**Comment by p-chan** [comment]
#8 にいろいろ書いてある
