### ISSUE TITLE
テーブルを決定する

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#5]
#4 からの派生Issue

円卓は厳しいってなったけど、やっぱり欲しいし、ここ結構初期運営の形を作っていきそうだから慎重に決めたい。
今日たまたまでかけた先にでかいニトリあったから寄ったけど、やっぱり6人掛けだと長方形しかなくて（しかも数自体限られる）、円卓の調達は困難を極めそう感じあるので、この間話にでてた四角机DIYになりそうかなー。

**Comment by p-chan** [comment]
以下の2つをDIYだと思う
- 6人座れる長方形の机
- 2人座れる正方形っぽい机

**Comment by potato4d** [comment]
DIYにかかる費用とか諸々調べないとね（あと部屋のサイズにもよるし）

**Comment by p-chan** [comment]
DIYに関しては、予算だけ決めてあとは近くのホームセンターに行ってみないと分からない説ある

**Comment by p-chan** [comment]
予算3万円で考える

**Comment by p-chan** [comment]
[10人まで - ダイニングテーブル - IKEA](http://www.ikea.com/jp/ja/catalog/categories/departments/dining/21828/)

京都のTHE Businessってスペースにあった, パソコン広げた人が6人座れると思った.
3万あれば買えるっぽいし, 神な予感がある.

**Comment by p-chan** [comment]
上記のリンクで決定で.
