### ISSUE TITLE
法人について調べる

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#6]

**Comment by potato4d** [comment]
一般社団法人だと資金面でやっぱ11万円はかかるね

この辺聞けるところってどこだろう。役所？

**Comment by potato4d** [comment]
あと非営利になるから、「利益出たら分配」がダメで、「給料ならok」という物凄く微妙なものだから、法人の種類はもう一回ちゃんと話すほうがよさそう

**Comment by p-chan** [comment]
今のところ必要ない、必要性が出てきたら再考する。
