### ISSUE TITLE
9月何やるか議論

### ISSUE THREAD

**Issue by potato4d** [the-house-of-ohnin/issues#8]
- 入居手続き及び持ち込み荷物搬入
- 備品の購入及び設営

**Comment by potato4d** [comment]
9月, 10月はとりあえず法人化はナシで

**Comment by potato4d** [comment]
ロゴを作る

**Comment by p-chan** [comment]
おかね：もの

50 家

5 椅子x6 [これ](https://www.nitori-net.jp/store/ja/ec/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%BB%E3%83%81%E3%82%A7%E3%82%A2%E3%83%BB%E6%96%87%E6%88%BF%E5%85%B7/%E3%83%87%E3%82%B9%E3%82%AF%E3%83%81%E3%82%A7%E3%82%A2%E3%83%BB%E3%82%AA%E3%83%95%E3%82%A3%E3%82%B9%E3%83%81%E3%82%A7%E3%82%A2/6620405s)
3 机
0.5 レンジ
1 ディスプレイ
1.5 炊飯器
1 冷蔵庫
2 インターネット
2 ルーター

**Comment by potato4d** [comment]
課題:持ち込み物の所有権

**Comment by potato4d** [comment]
2ch.net/before.html

**Comment by potato4d** [comment]
http://www.yodobashi.com/ec/product/100000001002847248/index.html?gad1=&gad2=g&gad3=&gad4=56278881131&gad5=11087586923996373018&gad6=1o1&xfr=pla&gclid=CPH55Zqio84CFQwjvQodn0IFeQ

**Comment by potato4d** [comment]
あとでスプレッドシートをはる

**Comment by potato4d** [comment]
https://docs.google.com/a/potato4d.me/spreadsheets/d/11LOBMePwYzxfiIyUQhCvo0RQfg_Xo3_ynVI3cZen2O0/htmlview

**Comment by p-chan** [comment]
ちょっとややこしくなりすぎたのでクローズしますよ
